name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  push_to_registry:

    runs-on: ubuntu-latest
    env: 
      TOPLEVEL: ghcr.io
      REPOSITORY: $(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
      IMAGE: ribiosmath
      
    steps:
        - name: Test
          run: echo ${{env.TOPLEVEL}}/${{env.REPOSITORY}}/${{env.IMAGE}}:${{ github.sha }}
    
        - name: Check out the REPOSITORY
          uses: actions/checkout@v2
          
        - name: Login to the GitHub Container Registry
          run:  echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.TOPLEVEL }} -u ${{ github.actor }} --password-stdin
          
        - name: Build the Docker image
          run: |
                docker build -t ${{env.TOPLEVEL}}/${{env.REPOSITORY}}/${{env.IMAGE}} . 
               
        - name: Push the Docker image to the registry
          run: |
                docker push ${{env.TOPLEVEL}}/${{env.REPOSITORY}}/${{env.IMAGE}}:${{ github.sha }} 
                docker push ${{env.TOPLEVEL}}/${{env.REPOSITORY}}/${{env.IMAGE}}:latest
