name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  push_to_registry:

    runs-on: ubuntu-latest
    env: 
      TOPLEVEL: ghcr.io
      IMAGE: ribiosmath
      
    steps:
        - name: Test
          run: echo "REPOSITORY=${{ env.TOPLEVEL }}/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/${{ env.IMAGE }}" >> $GITHUB_ENV
    
        - name: Check out the REPOSITORY
          uses: actions/checkout@v2
          
        - name: Login to the GitHub Container Registry
          run:  echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.TOPLEVEL }} -u ${{ github.actor }} --password-stdin
          
        - name: Build the Docker image
          run: |
                docker build -t ${{ env.REPOSITORY }}:${{ github.sha }} -t ${{ env.REPOSITORY }}:latest . 
               
        - name: Push the Docker image to the registry
          run: |
                docker push ${{ env.REPOSITORY }}:${{ github.sha }} 
                docker push ${{ env.REPOSITORY }}:latest
