name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  push_to_registry:

    runs-on: ubuntu-latest

    steps:
        - name: Check out the repo
          uses: actions/checkout@v2
        - name: Log in to GitHub Docker Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Get Repository Name
          run: REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]') 
        - name: Build container image
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: |
             ghcr.io/$REPOSITORY/dockerimage:${{ github.sha }}
             ghcr.io/$REPOSITORY/dockerimage:latest
